//! GENERATED by `cargo xtask bake-kits` — DO NOT EDIT.
//!
//! Source of truth: `crates/drumlin/kits/*.kit.json` (the graduated
//! library; see that folder's README for the listening-session flow).
//! Re-run the bake after adding/culling kits. Validated crate-side by
//! the factory tests (row decode, terrain registration, id uniqueness,
//! finite render).

use crate::kits::Kit;

pub static BAKED_KITS: &[&Kit] = &[];
